name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "seanmorris17@gmail.com"
          git config --global user.name "sm110101"
          git remote add space https://huggingface.co/spaces/sm110101/YOLO-to-GIF
          git push hf main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
